### ISSUE TITLE
Provide a manifest function to be used outside of templates

### ISSUE THREAD

**Issue by jkevingutierrez** [shonin/django-manifest-loader#28]
It would be good to have a function `manifest` that could be used outside of the templates (in python files). Something similar to the Django `static` function: https://github.com/django/django/blob/master/django/templatetags/static.py#L162

**Comment by jkevingutierrez** [comment]
Hi @shonin Thanks for your work on this. I just saw the `waiting release` label. Is there anything that you need help with to publish a new version?

**Comment by shonin** [comment]
Hi @jkevingutierrez this change introduces some restructuring of the API, which means I'll need to do a major version bump. I've been sitting on it so that I can see if there's anything else I want to change before publication.  I have one change on my local machine I need to push up and then I'll get v1.0.0 published tonight

**Comment by rykener** [comment]
@jkevingutierrez sorry for the delay. v1 has been published this morning. Documentation here: https://django-manifest-loader.readthedocs.io/en/stable/docs/usage.html#use-outside-of-templates
